version: '3'
services:
  trimmomatic:
    build: ./trimmomatic
    volumes:
     - ./trimmomatic:/src/trimmomatic/
     - ./working:/working/
  star:
    build: ./star
    volumes:
     - ./working:/working/
    ports:
     - 5000:80
    depends_on:
     - trimmomatic
  multiqc:
    build: ./star
    volumes:
     - ./working:/working/
    depends_on:
     - trimmomatic
     - star
